//
//  GCodeParser.swift
//  Stratum CNC
//
//  Created by Cristian Baluta on 16.09.2026.
//

import Foundation
import simd

// Reference https://howtomechatronics.com/tutorials/g-code-explained-list-of-most-important-g-code-commands/

private enum GCodeMotion {
    case rapid
    case linear
    case clockwiseArc
    case counterClockwiseArc
}

private enum GCodeUnits {

    case millimeters
    case inches

    var scaleToMillimeters: Double {

        switch self {

        case .millimeters:
            return 1.0

        case .inches:
            return 25.4
        }
    }
}

private struct GCodeState {
    /// Current machine/work position in millimeters.
    var position = SIMD3<Double>(0, 0, 0)
    /// Current modal motion.
    var motion: GCodeMotion = .rapid
    /// Current units.
    var units: GCodeUnits = .millimeters
    /// G90 = true
    /// G91 = false
    var absolutePositioning = true
    /// Current feed rate.
    var feedRate: Double = 0
}

struct ParsedGCode: Sendable {
    let lines: [GCodeLine]
    let toolpathSegments: [ToolpathSegment]
    /// Metadata from the file's leading comment block, if one of the
    /// parser's `GCodeHeaderParser`s recognised it.
    let header: GCodeHeader?
}

/// One line of a loaded G-code / NC program.
struct GCodeLine: Identifiable, Hashable, Sendable {
    /// `id` is the 1-based line number. This is also the value that can be
    /// compared with the machine's P: status field.
    let id: Int
    /// Original source text without the line ending.
    var text: String
    /// Index of the first generated toolpath segment for this line.
    /// If this line generates no geometry, this will equal `geometryStart`
    /// but `geometryCount` will be zero.
    var geometryStart: Int = 0
    /// Number of toolpath segments generated by this G-code line.
    var geometryCount: Int = 0
}

/// A single renderable toolpath segment.
///
/// This is deliberately kept simple so it can later be copied directly into
/// a Metal buffer or converted into whatever vertex representation the
/// renderer needs.
struct ToolpathSegment: Hashable, Sendable {
    /// Start point in millimeters.
    let start: SIMD3<Float>
    /// End point in millimeters.
    let end: SIMD3<Float>
    /// Original 1-based G-code line that produced this segment.
    let lineNumber: UInt32
    /// ToolpathFlags.
    let flags: UInt32
}

/// Flags describing the type of a toolpath segment.
enum ToolpathFlags {
    /// G0 / rapid movement.
    static let rapid: UInt32 = 1 << 0
    /// G1 / cutting movement.
    static let cutting: UInt32 = 1 << 1
    /// G2 / G3 arc movement.
    static let arc: UInt32 = 1 << 2
}

final class GCodeParser {

    /// Tried in order against the file's leading comment block; the first
    /// one that recognises it wins. Add support for another CAM's header by
    /// writing a `GCodeHeaderParser` and listing it here.
    private let headerParsers: [any GCodeHeaderParser]

    /// Safety cap on how much of the top of a file is treated as "header",
    /// so a file that's nothing but comments isn't scanned end to end.
    private static let maxHeaderLines = 1000

    init(headerParsers: [any GCodeHeaderParser] = [MakeraHeaderParser()]) {
        self.headerParsers = headerParsers
    }

    func parse(_ contents: String) -> ParsedGCode {

        var lines: [GCodeLine] = []
        var toolpathSegments: [ToolpathSegment] = []

        // This is only an estimate. It reduces reallocations without
        // assuming a particular file size.
        lines.reserveCapacity(max(1024, contents.utf8.count / 32))
        toolpathSegments.reserveCapacity(max(1024, contents.utf8.count / 64))

        var state = GCodeState()

        var lineNumber = 0

        contents.enumerateLines { text, _ in

            lineNumber += 1

            let geometryStart = toolpathSegments.count

            self.parseLine(text,
                           lineNumber: lineNumber,
                           state: &state,
                           segments: &toolpathSegments)

            let geometryCount = toolpathSegments.count - geometryStart

            lines.append(
                GCodeLine(id: lineNumber,
                          text: text,
                          geometryStart: geometryStart,
                          geometryCount: geometryCount)
            )
        }

        return ParsedGCode(lines: lines,
                           toolpathSegments: toolpathSegments,
                           header: parseHeader(from: lines))
    }

    // MARK: Header

    /// Collects the leading run of comment/blank lines (up to the first line
    /// of actual code) and offers it to each header parser in turn.
    private func parseHeader(from lines: [GCodeLine]) -> GCodeHeader? {
        guard !headerParsers.isEmpty else {
            return nil
        }

        var headerLines: [String] = []
        for line in lines.prefix(Self.maxHeaderLines) {
            let trimmed = line.text.trimmingCharacters(in: .whitespaces)
            guard trimmed.isEmpty || trimmed.hasPrefix(";") || trimmed.hasPrefix("(") else {
                break
            }
            headerLines.append(line.text)
        }
        guard !headerLines.isEmpty else {
            return nil
        }

        for parser in headerParsers {
            if let header = parser.parse(headerLines: headerLines) {
                return header
            }
        }
        return nil
    }

    // MARK: Parse line

    private func parseLine(_ text: String, lineNumber: Int, state: inout GCodeState, segments: inout [ToolpathSegment]) {

        let bytes = Array(text.utf8)
        var values: [UInt8: Double] = [:]
        var gCommands: [Int] = []
        var mCommands: [Int] = []
        var index = 0

        while index < bytes.count {
            let byte = bytes[index]
            // Parenthesized comment.
            if byte == 0x28 { // (
                while index < bytes.count &&
                      bytes[index] != 0x29 {
                    index += 1
                }
                if index < bytes.count {
                    index += 1
                }
                continue
            }

            // Semicolon comment.
            if byte == 0x3B { // ;
                break
            }

            let upper = byte >= 97 && byte <= 122 ? byte - 32 : byte

            // G command.
            if upper == 0x47 { // G
                index += 1
                if let number = parseNumber(bytes, index: &index) {
                    gCommands.append(Int(number))
                }
                continue
            }

            // M command.
            if upper == 0x4D { // M
                index += 1
                if let number = parseNumber(bytes, index: &index) {
                    mCommands.append(Int(number))
                }
                continue
            }

            // Coordinate / arc values.
            if isCoordinateLetter(upper) {
                index += 1
                if let value = parseNumber(bytes, index: &index) {
                    values[upper] = value
                }
                continue
            }

            // Feed rate.
            if upper == 0x46 { // F

                index += 1

                if let value = parseNumber(
                    bytes,
                    index: &index
                ) {
                    state.feedRate = value
                }

                continue
            }

            index += 1
        }

        // M commands don't currently generate geometry, but we intentionally
        // parse them so the parser can be expanded later.
        _ = mCommands

        // Apply all G-code modal commands in their original order.
        for g in gCommands {
            applyGCommand(
                g,
                state: &state
            )
        }

        // Current position before this line.
        let oldPosition = state.position

        var newPosition = oldPosition

        let scale =
            state.units.scaleToMillimeters

        // X
        if let value = values[0x58] {

            let scaled = value * scale

            if state.absolutePositioning {
                newPosition.x = scaled
            } else {
                newPosition.x += scaled
            }
        }

        // Y
        if let value = values[0x59] {

            let scaled = value * scale

            if state.absolutePositioning {
                newPosition.y = scaled
            } else {
                newPosition.y += scaled
            }
        }

        // Z
        if let value = values[0x5A] {

            let scaled = value * scale

            if state.absolutePositioning {
                newPosition.z = scaled
            } else {
                newPosition.z += scaled
            }
        }

        let hasXYZ =
            values[0x58] != nil ||
            values[0x59] != nil ||
            values[0x5A] != nil

        guard hasXYZ else {
            return
        }

        switch state.motion {

        case .rapid:

            appendLinearSegment(
                start: oldPosition,
                end: newPosition,
                lineNumber: lineNumber,
                flags: ToolpathFlags.rapid,
                segments: &segments
            )

        case .linear:

            appendLinearSegment(
                start: oldPosition,
                end: newPosition,
                lineNumber: lineNumber,
                flags: ToolpathFlags.cutting,
                segments: &segments
            )

        case .clockwiseArc:

            appendArc(
                start: oldPosition,
                end: newPosition,
                values: values,
                clockwise: true,
                scale: scale,
                lineNumber: lineNumber,
                segments: &segments
            )

        case .counterClockwiseArc:

            appendArc(
                start: oldPosition,
                end: newPosition,
                values: values,
                clockwise: false,
                scale: scale,
                lineNumber: lineNumber,
                segments: &segments
            )
        }

        state.position = newPosition
    }

    // MARK: G commands

    private func applyGCommand(_ g: Int, state: inout GCodeState) {
        switch g {
            case 0:
                state.motion = .rapid
            case 1:
                state.motion = .linear
            case 2:
                state.motion = .clockwiseArc
            case 3:
                state.motion = .counterClockwiseArc
            case 20:
                state.units = .inches
            case 21:
                state.units = .millimeters
            case 90:
                state.absolutePositioning = true
            case 91:
                state.absolutePositioning = false
            default:
                break
        }
    }

    // MARK: Linear movement

    private func appendLinearSegment(
        start: SIMD3<Double>,
        end: SIMD3<Double>,
        lineNumber: Int,
        flags: UInt32,
        segments: inout [ToolpathSegment]
    ) {

        guard distanceSquared(
            start,
            end
        ) > 0.0000000001 else {
            return
        }

        segments.append(
            ToolpathSegment(
                start: SIMD3<Float>(
                    Float(start.x),
                    Float(start.y),
                    Float(start.z)
                ),
                end: SIMD3<Float>(
                    Float(end.x),
                    Float(end.y),
                    Float(end.z)
                ),
                lineNumber: UInt32(lineNumber),
                flags: flags
            )
        )
    }

    // MARK: Arc movement

    /// Tessellates a G2/G3 XY-plane arc into line segments.
    ///
    /// I/J are interpreted as incremental center offsets, which is the
    /// standard convention for common CNC G-code.
    private func appendArc(start: SIMD3<Double>,
                           end: SIMD3<Double>,
                           values: [UInt8: Double],
                           clockwise: Bool,
                           scale: Double,
                           lineNumber: Int,
                           segments: inout [ToolpathSegment]) {

        guard let iValue = values[0x49],
              let jValue = values[0x4A] else {

            // If the arc cannot be resolved, safely fall back to a straight
            // line rather than generating invalid geometry.
            appendLinearSegment(start: start,
                                end: end,
                                lineNumber: lineNumber,
                                flags: ToolpathFlags.arc,
                                segments: &segments)
            return
        }

        let center = SIMD2<Double>(
            start.x + iValue * scale,
            start.y + jValue * scale
        )

        let startVector = SIMD2<Double>(
            start.x - center.x,
            start.y - center.y
        )

        let endVector = SIMD2<Double>(
            end.x - center.x,
            end.y - center.y
        )

        let radius =
            simd_length(startVector)

        guard radius > 0.000001 else {

            appendLinearSegment(
                start: start,
                end: end,
                lineNumber: lineNumber,
                flags: ToolpathFlags.arc,
                segments: &segments
            )

            return
        }

        let startAngle = atan2(startVector.y, startVector.x)
        let endAngle = atan2(endVector.y, endVector.x)
        var delta = endAngle - startAngle

        if clockwise {
            if delta >= 0 {
                delta -= 2.0 * Double.pi
            }
        } else {
            if delta <= 0 {
                delta += 2.0 * Double.pi
            }
        }

        // 5-degree maximum angular step.
        //
        // This gives reasonably smooth geometry for a CNC viewer while
        // keeping the number of generated segments under control.
        let maximumAngle = Double.pi / 36.0
        let segmentCount = max(1, Int(ceil(abs(delta) / maximumAngle)))
        var previous = start

        for segmentIndex in 1...segmentCount {

            let t =
                Double(segmentIndex) /
                Double(segmentCount)

            let angle = startAngle + delta * t

            let point = SIMD3<Double>(
                center.x + cos(angle) * radius,
                center.y + sin(angle) * radius,
                // Interpolate Z along the arc.
                start.z + (end.z - start.z) * t
            )

            appendLinearSegment(start: previous,
                                end: point,
                                lineNumber: lineNumber,
                                flags: ToolpathFlags.arc,
                                segments: &segments)

            previous = point
        }
    }

    // MARK: Number parsing

    private func parseNumber(_ bytes: [UInt8], index: inout Int) -> Double? {

        let start = index

        // Sign.
        if index < bytes.count && (bytes[index] == 0x2B || bytes[index] == 0x2D) {
            index += 1
        }
        var hasDigits = false

        // Integer portion.
        while index < bytes.count {
            let byte = bytes[index]
            if byte >= 48 && byte <= 57 {
                hasDigits = true
                index += 1
            } else {
                break
            }
        }

        // Decimal point.
        if index < bytes.count &&
           bytes[index] == 0x2E {

            index += 1

            while index < bytes.count {
                let byte = bytes[index]
                if byte >= 48 && byte <= 57 {
                    hasDigits = true
                    index += 1
                } else {
                    break
                }
            }
        }

        // Scientific notation.
        if index < bytes.count {
            let byte = bytes[index]

            if byte == 0x45 || byte == 0x65 { // E/e
                let exponentStart = index
                index += 1

                if index < bytes.count && (bytes[index] == 0x2B || bytes[index] == 0x2D) {
                    index += 1
                }

                var exponentHasDigits = false

                while index < bytes.count {
                    let digit = bytes[index]
                    if digit >= 48 && digit <= 57 {
                        exponentHasDigits = true
                        index += 1
                    } else {
                        break
                    }
                }

                if !exponentHasDigits {
                    index = exponentStart
                }
            }
        }

        guard hasDigits else {
            index = start
            return nil
        }

        return Double(String(decoding: bytes[start..<index], as: UTF8.self))
    }

    // MARK: Helpers

    private func isCoordinateLetter(_ byte: UInt8) -> Bool {
        switch byte {
            case 0x58, // X
                0x59, // Y
                0x5A, // Z
                0x49, // I
                0x4A, // J
                0x4B: // K
                return true
            default:
                return false
        }
    }

    private func distanceSquared(_ a: SIMD3<Double>, _ b: SIMD3<Double>) -> Double {
        let d = a - b
        return d.x*d.x + d.y*d.y + d.z*d.z
    }
}
