import Foundation
import Combine
import simd

// MARK: - G-code line

/// One line of a loaded G-code / NC program.
///
/// `id` is the 1-based line number. This is also the value that can be
/// compared with the machine's P: status field.
struct GCodeLine: Identifiable, Hashable, Sendable {
    let id: Int
    /// Original source text without the line ending.
    var text: String
    /// Index of the first generated toolpath segment for this line.
    ///
    /// If this line generates no geometry, this will equal `geometryStart`
    /// but `geometryCount` will be zero.
    var geometryStart: Int = 0
    /// Number of toolpath segments generated by this G-code line.
    var geometryCount: Int = 0
}


// MARK: - Toolpath geometry

/// A single renderable toolpath segment.
///
/// This is deliberately kept simple so it can later be copied directly into
/// a Metal buffer or converted into whatever vertex representation the
/// renderer needs.
struct ToolpathSegment: Hashable, Sendable {

    /// Start point in millimeters.
    let start: SIMD3<Float>

    /// End point in millimeters.
    let end: SIMD3<Float>

    /// Original 1-based G-code line that produced this segment.
    let lineNumber: UInt32

    /// ToolpathFlags.
    let flags: UInt32
}

/// Flags describing the type of a toolpath segment.
enum ToolpathFlags {
    /// G0 / rapid movement.
    static let rapid: UInt32 = 1 << 0
    /// G1 / cutting movement.
    static let cutting: UInt32 = 1 << 1
    /// G2 / G3 arc movement.
    static let arc: UInt32 = 1 << 2
}

// MARK: - G-code modal state

private enum GCodeMotion {
    case rapid
    case linear
    case clockwiseArc
    case counterClockwiseArc
}

private enum GCodeUnits {

    case millimeters
    case inches

    var scaleToMillimeters: Double {

        switch self {

        case .millimeters:
            return 1.0

        case .inches:
            return 25.4
        }
    }
}

private struct GCodeState {
    /// Current machine/work position in millimeters.
    var position = SIMD3<Double>(0, 0, 0)
    /// Current modal motion.
    var motion: GCodeMotion = .rapid
    /// Current units.
    var units: GCodeUnits = .millimeters
    /// G90 = true
    /// G91 = false
    var absolutePositioning = true
    /// Current feed rate.
    var feedRate: Double = 0
}

// MARK: - Parsed result

/// Everything produced by the background parser.
///
/// All properties are value types and Sendable, which makes this safe to
/// return across Swift concurrency boundaries.
private struct ParsedGCode: Sendable {
    let lines: [GCodeLine]
    let toolpathSegments: [ToolpathSegment]
}

// MARK: - NC file document

@MainActor
final class NCFileDocument: ObservableObject {

    // MARK: Published state

    @Published private(set) var fileURL: URL?
    @Published private(set) var fileName: String = "No file loaded"
    @Published private(set) var lines: [GCodeLine] = []
    @Published private(set) var toolpathSegments: [ToolpathSegment] = []
    @Published private(set) var isLoading: Bool = false
    @Published var lastError: String?

    // MARK: Convenience properties

    var isLoaded: Bool {
        fileURL != nil
    }

    var lineCount: Int {
        lines.count
    }

    var toolpathCount: Int {
        toolpathSegments.count
    }

    // MARK: Internal task

    private var loadTask: Task<Void, Never>?

    // MARK: Load

    /// Loads and parses the complete file.
    ///
    /// The file is kept in memory because G-code files for this application
    /// are normally only a few MB. Parsing is performed away from the main
    /// actor so a large file does not freeze the UI.
    func load(from url: URL) {

        loadTask?.cancel()

        lastError = nil
        isLoading = true

        let fileName = url.lastPathComponent

        loadTask = Task { [weak self] in

            do {
                let parsed = try await Self.parseFile(url: url)

                guard !Task.isCancelled else {
                    return
                }
                guard let self else {
                    return
                }

                self.lines = parsed.lines
                self.toolpathSegments = parsed.toolpathSegments
                self.fileURL = url
                self.fileName = fileName
                self.isLoading = false

            } catch {

                guard !Task.isCancelled else {
                    return
                }
                guard let self else {
                    return
                }

                self.isLoading = false
                self.lastError = "Couldn't read file: \(error.localizedDescription)"
            }
        }
    }

    func load(from string: String) {
        let parser = GCodeParser()
        let code: ParsedGCode = parser.parse(string)

        self.lines = code.lines
        self.toolpathSegments = code.toolpathSegments
        self.fileName = "From CAM"
    }

    // MARK: Background parsing

    /// Loads and parses the complete file away from the main actor.
    ///
    /// Only Sendable value types cross back to the MainActor.
    private nonisolated static func parseFile(url: URL) async throws -> ParsedGCode {

        let didStartAccess = url.startAccessingSecurityScopedResource()

        defer {
            if didStartAccess {
                url.stopAccessingSecurityScopedResource()
            }
        }

        // The complete file is intentionally kept in memory.
        //
        // For the expected file sizes this is substantially simpler and
        // faster for NSTableView than repeatedly reading from disk.
        let contents = try String(contentsOf: url, encoding: .utf8)
        let parser = GCodeParser()

        return parser.parse(contents)
    }

    // MARK: Line editing

    /// Updates a single line.
    ///
    /// Note:
    /// Changing a G-code line can affect all subsequent modal state and
    /// therefore potentially changes the entire toolpath.
    ///
    /// For that reason we update the text here and then rebuild the complete
    /// model. For files of a few MB this is a reasonable and safe approach.
    func updateLine(at index: Int, text: String) {

        guard index >= 0, index < lines.count else {
            return
        }
        guard lines[index].text != text else {
            return
        }

        lines[index].text = text

        rebuildToolpath()
    }

    /// Rebuilds the toolpath from the current in-memory lines.
    ///
    /// This is useful after editing.
    func rebuildToolpath() {

        let source = lines
            .map(\.text)
            .joined(separator: "\n")

        let parser = GCodeParser()
        let parsed = parser.parse(source)

        lines = parsed.lines
        toolpathSegments = parsed.toolpathSegments
    }

    // MARK: Geometry lookup

    /// Returns the toolpath geometry generated by a particular G-code line.
    ///
    /// `lineNumber` is 1-based, matching the machine's P: value.
    func geometry(forLine lineNumber: Int) -> ArraySlice<ToolpathSegment> {

        let index = lineNumber - 1

        guard index >= 0, index < lines.count else {
            return toolpathSegments[0..<0]
        }

        let line = lines[index]

        let start = line.geometryStart
        let end = start + line.geometryCount

        guard start >= 0, end <= toolpathSegments.count, start <= end else {
            return toolpathSegments[0..<0]
        }

        return toolpathSegments[start..<end]
    }

    // MARK: Machine line lookup

    /// Returns the table row corresponding to a machine P: line number.
    ///
    /// P: values are 1-based, so this simply converts to a zero-based array
    /// index.
    func tableIndex(forMachineLine lineNumber: Int) -> Int? {

        let index = lineNumber - 1

        guard index >= 0, index < lines.count else {
            return nil
        }

        return index
    }

    // MARK: Clear

    func clear() {

        loadTask?.cancel()
        loadTask = nil

        fileURL = nil
        fileName = "No file loaded"

        lines.removeAll()
        toolpathSegments.removeAll()

        lastError = nil
        isLoading = false
    }
}


// MARK: - G-code parser

private final class GCodeParser {

    func parse(_ contents: String) -> ParsedGCode {

        var lines: [GCodeLine] = []

        var toolpathSegments: [ToolpathSegment] = []

        // This is only an estimate. It reduces reallocations without
        // assuming a particular file size.
        lines.reserveCapacity(
            max(1024, contents.utf8.count / 32)
        )

        toolpathSegments.reserveCapacity(
            max(1024, contents.utf8.count / 64)
        )

        var state = GCodeState()

        var lineNumber = 0

        contents.enumerateLines { text, _ in

            lineNumber += 1

            let geometryStart = toolpathSegments.count

            self.parseLine(
                text,
                lineNumber: lineNumber,
                state: &state,
                segments: &toolpathSegments
            )

            let geometryCount =
                toolpathSegments.count - geometryStart

            lines.append(
                GCodeLine(
                    id: lineNumber,
                    text: text,
                    geometryStart: geometryStart,
                    geometryCount: geometryCount
                )
            )
        }

        return ParsedGCode(
            lines: lines,
            toolpathSegments: toolpathSegments
        )
    }

    // MARK: Parse line

    private func parseLine(
        _ text: String,
        lineNumber: Int,
        state: inout GCodeState,
        segments: inout [ToolpathSegment]
    ) {

        let bytes = Array(text.utf8)

        var values: [UInt8: Double] = [:]

        var gCommands: [Int] = []

        var mCommands: [Int] = []

        var index = 0

        while index < bytes.count {

            let byte = bytes[index]

            // Parenthesized comment.
            if byte == 0x28 { // (

                while index < bytes.count &&
                      bytes[index] != 0x29 {
                    index += 1
                }

                if index < bytes.count {
                    index += 1
                }

                continue
            }

            // Semicolon comment.
            if byte == 0x3B { // ;
                break
            }

            let upper =
                byte >= 97 && byte <= 122
                ? byte - 32
                : byte

            // G command.
            if upper == 0x47 { // G

                index += 1

                if let number = parseNumber(
                    bytes,
                    index: &index
                ) {
                    gCommands.append(Int(number))
                }

                continue
            }

            // M command.
            if upper == 0x4D { // M

                index += 1

                if let number = parseNumber(
                    bytes,
                    index: &index
                ) {
                    mCommands.append(Int(number))
                }

                continue
            }

            // Coordinate / arc values.
            if isCoordinateLetter(upper) {

                index += 1

                if let value = parseNumber(
                    bytes,
                    index: &index
                ) {
                    values[upper] = value
                }

                continue
            }

            // Feed rate.
            if upper == 0x46 { // F

                index += 1

                if let value = parseNumber(
                    bytes,
                    index: &index
                ) {
                    state.feedRate = value
                }

                continue
            }

            index += 1
        }

        // M commands don't currently generate geometry, but we intentionally
        // parse them so the parser can be expanded later.
        _ = mCommands

        // Apply all G-code modal commands in their original order.
        for g in gCommands {
            applyGCommand(
                g,
                state: &state
            )
        }

        // Current position before this line.
        let oldPosition = state.position

        var newPosition = oldPosition

        let scale =
            state.units.scaleToMillimeters

        // X
        if let value = values[0x58] {

            let scaled = value * scale

            if state.absolutePositioning {
                newPosition.x = scaled
            } else {
                newPosition.x += scaled
            }
        }

        // Y
        if let value = values[0x59] {

            let scaled = value * scale

            if state.absolutePositioning {
                newPosition.y = scaled
            } else {
                newPosition.y += scaled
            }
        }

        // Z
        if let value = values[0x5A] {

            let scaled = value * scale

            if state.absolutePositioning {
                newPosition.z = scaled
            } else {
                newPosition.z += scaled
            }
        }

        let hasXYZ =
            values[0x58] != nil ||
            values[0x59] != nil ||
            values[0x5A] != nil

        guard hasXYZ else {
            return
        }

        switch state.motion {

        case .rapid:

            appendLinearSegment(
                start: oldPosition,
                end: newPosition,
                lineNumber: lineNumber,
                flags: ToolpathFlags.rapid,
                segments: &segments
            )

        case .linear:

            appendLinearSegment(
                start: oldPosition,
                end: newPosition,
                lineNumber: lineNumber,
                flags: ToolpathFlags.cutting,
                segments: &segments
            )

        case .clockwiseArc:

            appendArc(
                start: oldPosition,
                end: newPosition,
                values: values,
                clockwise: true,
                scale: scale,
                lineNumber: lineNumber,
                segments: &segments
            )

        case .counterClockwiseArc:

            appendArc(
                start: oldPosition,
                end: newPosition,
                values: values,
                clockwise: false,
                scale: scale,
                lineNumber: lineNumber,
                segments: &segments
            )
        }

        state.position = newPosition
    }

    // MARK: G commands

    private func applyGCommand(
        _ g: Int,
        state: inout GCodeState
    ) {

        switch g {

        case 0:
            state.motion = .rapid

        case 1:
            state.motion = .linear

        case 2:
            state.motion = .clockwiseArc

        case 3:
            state.motion = .counterClockwiseArc

        case 20:
            state.units = .inches

        case 21:
            state.units = .millimeters

        case 90:
            state.absolutePositioning = true

        case 91:
            state.absolutePositioning = false

        default:
            break
        }
    }

    // MARK: Linear movement

    private func appendLinearSegment(
        start: SIMD3<Double>,
        end: SIMD3<Double>,
        lineNumber: Int,
        flags: UInt32,
        segments: inout [ToolpathSegment]
    ) {

        guard distanceSquared(
            start,
            end
        ) > 0.0000000001 else {
            return
        }

        segments.append(
            ToolpathSegment(
                start: SIMD3<Float>(
                    Float(start.x),
                    Float(start.y),
                    Float(start.z)
                ),
                end: SIMD3<Float>(
                    Float(end.x),
                    Float(end.y),
                    Float(end.z)
                ),
                lineNumber: UInt32(lineNumber),
                flags: flags
            )
        )
    }

    // MARK: Arc movement

    /// Tessellates a G2/G3 XY-plane arc into line segments.
    ///
    /// I/J are interpreted as incremental center offsets, which is the
    /// standard convention for common CNC G-code.
    private func appendArc(
        start: SIMD3<Double>,
        end: SIMD3<Double>,
        values: [UInt8: Double],
        clockwise: Bool,
        scale: Double,
        lineNumber: Int,
        segments: inout [ToolpathSegment]
    ) {

        guard let iValue = values[0x49],
              let jValue = values[0x4A]
        else {

            // If the arc cannot be resolved, safely fall back to a straight
            // line rather than generating invalid geometry.
            appendLinearSegment(
                start: start,
                end: end,
                lineNumber: lineNumber,
                flags: ToolpathFlags.arc,
                segments: &segments
            )

            return
        }

        let center = SIMD2<Double>(
            start.x + iValue * scale,
            start.y + jValue * scale
        )

        let startVector = SIMD2<Double>(
            start.x - center.x,
            start.y - center.y
        )

        let endVector = SIMD2<Double>(
            end.x - center.x,
            end.y - center.y
        )

        let radius =
            simd_length(startVector)

        guard radius > 0.000001 else {

            appendLinearSegment(
                start: start,
                end: end,
                lineNumber: lineNumber,
                flags: ToolpathFlags.arc,
                segments: &segments
            )

            return
        }

        let startAngle =
            atan2(
                startVector.y,
                startVector.x
            )

        let endAngle =
            atan2(
                endVector.y,
                endVector.x
            )

        var delta =
            endAngle - startAngle

        if clockwise {

            if delta >= 0 {
                delta -= 2.0 * Double.pi
            }

        } else {

            if delta <= 0 {
                delta += 2.0 * Double.pi
            }
        }

        // 5-degree maximum angular step.
        //
        // This gives reasonably smooth geometry for a CNC viewer while
        // keeping the number of generated segments under control.
        let maximumAngle =
            Double.pi / 36.0

        let segmentCount =
            max(
                1,
                Int(
                    ceil(
                        abs(delta) / maximumAngle
                    )
                )
            )

        var previous = start

        for segmentIndex in 1...segmentCount {

            let t =
                Double(segmentIndex) /
                Double(segmentCount)

            let angle =
                startAngle +
                delta * t

            let point = SIMD3<Double>(
                center.x + cos(angle) * radius,
                center.y + sin(angle) * radius,

                // Interpolate Z along the arc.
                start.z +
                (end.z - start.z) * t
            )

            appendLinearSegment(
                start: previous,
                end: point,
                lineNumber: lineNumber,
                flags: ToolpathFlags.arc,
                segments: &segments
            )

            previous = point
        }
    }

    // MARK: Number parsing

    private func parseNumber(
        _ bytes: [UInt8],
        index: inout Int
    ) -> Double? {

        let start = index

        // Sign.
        if index < bytes.count &&
           (bytes[index] == 0x2B ||
            bytes[index] == 0x2D) {

            index += 1
        }

        var hasDigits = false

        // Integer portion.
        while index < bytes.count {

            let byte = bytes[index]

            if byte >= 48 && byte <= 57 {

                hasDigits = true
                index += 1

            } else {

                break
            }
        }

        // Decimal point.
        if index < bytes.count &&
           bytes[index] == 0x2E {

            index += 1

            while index < bytes.count {

                let byte = bytes[index]

                if byte >= 48 && byte <= 57 {

                    hasDigits = true
                    index += 1

                } else {

                    break
                }
            }
        }

        // Scientific notation.
        if index < bytes.count {

            let byte = bytes[index]

            if byte == 0x45 || byte == 0x65 { // E/e

                let exponentStart = index

                index += 1

                if index < bytes.count &&
                   (bytes[index] == 0x2B ||
                    bytes[index] == 0x2D) {

                    index += 1
                }

                var exponentHasDigits = false

                while index < bytes.count {

                    let digit = bytes[index]

                    if digit >= 48 && digit <= 57 {

                        exponentHasDigits = true
                        index += 1

                    } else {

                        break
                    }
                }

                if !exponentHasDigits {
                    index = exponentStart
                }
            }
        }

        guard hasDigits else {

            index = start

            return nil
        }

        return Double(
            String(
                decoding: bytes[start..<index],
                as: UTF8.self
            )
        )
    }

    // MARK: Helpers

    private func isCoordinateLetter(
        _ byte: UInt8
    ) -> Bool {

        switch byte {

        case 0x58, // X
             0x59, // Y
             0x5A, // Z
             0x49, // I
             0x4A, // J
             0x4B: // K

            return true

        default:
            return false
        }
    }

    private func distanceSquared(
        _ a: SIMD3<Double>,
        _ b: SIMD3<Double>
    ) -> Double {

        let d = a - b

        return
            d.x * d.x +
            d.y * d.y +
            d.z * d.z
    }
}
