//
//  NCFileDocument.swift
//  Stratum CNC
//
//  Created by Cristian Baluta on 26.08.2026.
//

import Foundation
import Combine
import simd

@MainActor
final class NCFileDocument: ObservableObject {

    @Published private(set) var fileURL: URL?
    @Published private(set) var fileName: String = "No file loaded"
    @Published private(set) var lines: [GCodeLine] = []
    @Published private(set) var toolpathSegments: [ToolpathSegment] = []
    @Published private(set) var isLoading: Bool = false
    @Published var lastError: String?

    var isLoaded: Bool {
        fileURL != nil
    }

    var lineCount: Int {
        lines.count
    }

    var toolpathCount: Int {
        toolpathSegments.count
    }

    // MARK: Load

    private var loadTask: Task<Void, Never>?

    func load(from url: URL) {

        loadTask?.cancel()

        lastError = nil
        isLoading = true

        let fileName = url.lastPathComponent

        loadTask = Task { [weak self] in
            do {
                let parsed = try await Self.loadAndParseFile(url: url)

                guard !Task.isCancelled else {
                    return
                }
                guard let self else {
                    return
                }

                self.lines = parsed.lines
                self.toolpathSegments = parsed.toolpathSegments
                self.fileURL = url
                self.fileName = fileName
                self.isLoading = false

            } catch {

                guard !Task.isCancelled else {
                    return
                }
                guard let self else {
                    return
                }

                self.isLoading = false
                self.lastError = "Couldn't read file: \(error.localizedDescription)"
            }
        }
    }

    func load(from string: String) {
        let parser = GCodeParser()
        let code: ParsedGCode = parser.parse(string)

        self.lines = code.lines
        self.toolpathSegments = code.toolpathSegments
        self.fileName = "From CAM"
    }

    // MARK: Background parsing

    private nonisolated static func loadAndParseFile(url: URL) async throws -> ParsedGCode {

        let didStartAccess = url.startAccessingSecurityScopedResource()
        defer {
            if didStartAccess {
                url.stopAccessingSecurityScopedResource()
            }
        }
        let contents = try String(contentsOf: url, encoding: .utf8)
        let parser = GCodeParser()

        return parser.parse(contents)
    }

    // MARK: Line editing

    func updateLine(at index: Int, text: String) {

        guard index >= 0, index < lines.count else {
            return
        }
        guard lines[index].text != text else {
            return
        }
        lines[index].text = text
        rebuildToolpath()
    }

    // TODO: this is not efficient at all
    func rebuildToolpath() {
        let source = lines.map(\.text).joined(separator: "\n")

        let parser = GCodeParser()
        let parsed = parser.parse(source)

        lines = parsed.lines
        toolpathSegments = parsed.toolpathSegments
    }

    // MARK: Geometry lookup

    func geometry(forLine lineNumber: Int) -> ArraySlice<ToolpathSegment> {

        let index = lineNumber - 1

        guard index >= 0, index < lines.count else {
            return toolpathSegments[0..<0]
        }

        let line = lines[index]

        let start = line.geometryStart
        let end = start + line.geometryCount

        guard start >= 0, end <= toolpathSegments.count, start <= end else {
            return toolpathSegments[0..<0]
        }

        return toolpathSegments[start..<end]
    }

    /// All toolpath segments generated by lines `1...line` (inclusive) — the
    /// prefix a scrubber should hand to `RenderObject.toolpath(from:)` so the
    /// canvas only draws what's been "cut" up to that point in the file.
    /// O(1): segments are appended in ascending line order while parsing, so
    /// a single line's own `geometryStart + geometryCount` (the same
    /// bookkeeping `geometry(forLine:)` uses) already marks where the prefix
    /// ends — no need to filter every segment by `lineNumber`.
    func toolpathSegments(upTo line: Int) -> ArraySlice<ToolpathSegment> {

        guard line >= 1 else {
            return toolpathSegments[0..<0]
        }
        guard !lines.isEmpty else {
            return toolpathSegments[0..<0]
        }

        let index = min(line, lines.count) - 1
        let end = lines[index].geometryStart + lines[index].geometryCount

        guard end >= 0, end <= toolpathSegments.count else {
            return toolpathSegments[0..<0]
        }

        return toolpathSegments[0..<end]
    }

    // MARK: Machine line lookup

    /// Returns the table row corresponding to a machine P: line number.
    ///
    /// P: values are 1-based, so this simply converts to a zero-based array
    /// index.
    func tableIndex(forMachineLine lineNumber: Int) -> Int? {

        let index = lineNumber - 1

        guard index >= 0, index < lines.count else {
            return nil
        }

        return index
    }

    // MARK: Clear

    func clear() {

        loadTask?.cancel()
        loadTask = nil

        fileURL = nil
        fileName = "No file loaded"

        lines.removeAll()
        toolpathSegments.removeAll()

        lastError = nil
        isLoading = false
    }
}
